services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portadent-django
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - redis
      - db

  redis:
    restart: always
    image: "redis:alpine"
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"

  mailhog:
    profiles:
      - debug
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A mysite.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A mysite.celery beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
