# Generated by Django 4.2.16 on 2024-10-24 19:13

import api.models.scan
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    (api.models.scan.ScanSourceType["WEB_APP"], "Web App"),
                    (api.models.scan.ScanSourceType["MOBILE_APP"], "Mobile App"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
