# Generated by Django 4.2.16 on 2024-10-24 21:25

import api.models.scan_photo
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_scan_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scanphoto",
            name="filename",
        ),
        migrations.AddField(
            model_name="scanphoto",
            name="file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.models.scan_photo.file_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="scanphoto",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_photos",
                to="api.scan",
            ),
        ),
        migrations.AlterField(
            model_name="scanresult",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_results",
                to="api.scan",
            ),
        ),
    ]
