# Generated by Django 4.2.16 on 2024-10-24 21:58

import api.models.scan_photo
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_scanphoto_filename_scanphoto_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanphoto",
            name="file",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[500, 300],
                upload_to=api.models.scan_photo.file_directory_path,
            ),
        ),
    ]
