# Generated by Django 4.2.16 on 2024-10-30 23:20

import api.models.scan
import api.models.scan_photo
import api.models.scan_result
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_scanphoto_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("WEB_APP", "WEB_APP"), ("MOBILE_APP", "MOBILE_APP")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "INITIALIZED"),
                    ("PHOTOS_FINISHED", "PHOTOS_FINISHED"),
                    ("FINISHED", "FINISHED"),
                ],
                default=api.models.scan.ScanStatusType["INITIALIZED"],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="scanphoto",
            name="file",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[300, 500],
                upload_to=api.models.scan_photo.file_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="scanphoto",
            name="type",
            field=models.CharField(
                choices=[
                    ("RIGHT", "RIGHT"),
                    ("LEFT", "LEFT"),
                    ("FRONT", "FRONT"),
                    ("LOWER", "LOWER"),
                    ("UPPER", "UPPER"),
                ],
                default=api.models.scan_photo.ScanPhotoType["FRONT"],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="scanresult",
            name="severity",
            field=models.CharField(
                choices=[("high", "HIGH"), ("medium", "MEDIUM"), ("low", "LOW")],
                default=api.models.scan_result.ScanResultSeverityType["LOW"],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="scanresult",
            name="tooth_type",
            field=models.CharField(
                choices=[
                    ("1", "TOOTH_1"),
                    ("2", "TOOTH_2"),
                    ("3", "TOOTH_3"),
                    ("4", "TOOTH_4"),
                    ("5", "TOOTH_5"),
                    ("6", "TOOTH_6"),
                    ("7", "TOOTH_7"),
                    ("8", "TOOTH_8"),
                    ("9", "TOOTH_9"),
                    ("10", "TOOTH_10"),
                    ("11", "TOOTH_11"),
                    ("12", "TOOTH_12"),
                    ("13", "TOOTH_13"),
                    ("14", "TOOTH_14"),
                    ("15", "TOOTH_15"),
                    ("16", "TOOTH_16"),
                    ("17", "TOOTH_17"),
                    ("18", "TOOTH_18"),
                    ("19", "TOOTH_19"),
                    ("20", "TOOTH_20"),
                    ("21", "TOOTH_21"),
                    ("22", "TOOTH_22"),
                    ("23", "TOOTH_23"),
                    ("24", "TOOTH_24"),
                    ("25", "TOOTH_25"),
                    ("26", "TOOTH_26"),
                    ("27", "TOOTH_27"),
                    ("28", "TOOTH_28"),
                    ("29", "TOOTH_29"),
                    ("30", "TOOTH_30"),
                    ("31", "TOOTH_31"),
                    ("32", "TOOTH_32"),
                    ("GUM_UPPER_LEFT_OUTSIDE", "GUM_UPPER_LEFT_OUTSIDE"),
                    ("GUM_UPPER_FRONT_OUTSIDE", "GUM_UPPER_FRONT_OUTSIDE"),
                    ("GUM_UPPER_RIGHT_OUTSIDE", "GUM_UPPER_RIGHT_OUTSIDE"),
                    ("GUM_LOWER_LEFT_OUTSIDE", "GUM_LOWER_LEFT_OUTSIDE"),
                    ("GUM_LOWER_FRONT_OUTSIDE", "GUM_LOWER_FRONT_OUTSIDE"),
                    ("GUM_LOWER_RIGHT_OUTSIDE", "GUM_LOWER_RIGHT_OUTSIDE"),
                    ("ROOF", "ROOF"),
                    ("TONGUE", "TONGUE"),
                ],
                default=api.models.scan_result.ScanResultToothType["TOOTH_11"],
                max_length=50,
            ),
        ),
    ]
