# Generated by Django 4.2.16 on 2024-10-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_scanphoto_type_alter_scanresult_severity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="source",
            field=models.CharField(
                choices=[("WEB_APP", "WEB_APP"), ("MOBILE_APP", "MOBILE_APP")],
                default="WEB_APP",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "INITIALIZED"),
                    ("PHOTOS_FINISHED", "PHOTOS_FINISHED"),
                    ("FINISHED", "FINISHED"),
                ],
                default="INITIALIZED",
                max_length=50,
            ),
        ),
    ]
