# Generated by Django 4.2.16 on 2024-10-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_scan_source_alter_scan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
