# Generated by Django 4.2.16 on 2024-10-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_scanresult_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='tooth_type',
            field=models.CharField(choices=[('11', 'TOOTH_11'), ('12', 'TOOTH_12'), ('13', 'TOOTH_13'), ('14', 'TOOTH_14'), ('15', 'TOOTH_15'), ('16', 'TOOTH_16'), ('17', 'TOOTH_17'), ('18', 'TOOTH_18'), ('21', 'TOOTH_21'), ('22', 'TOOTH_22'), ('23', 'TOOTH_23'), ('24', 'TOOTH_24'), ('25', 'TOOTH_25'), ('26', 'TOOTH_26'), ('27', 'TOOTH_27'), ('28', 'TOOTH_28'), ('31', 'TOOTH_31'), ('32', 'TOOTH_32'), ('33', 'TOOTH_33'), ('34', 'TOOTH_34'), ('35', 'TOOTH_35'), ('36', 'TOOTH_36'), ('37', 'TOOTH_37'), ('38', 'TOOTH_38'), ('41', 'TOOTH_41'), ('42', 'TOOTH_42'), ('43', 'TOOTH_43'), ('44', 'TOOTH_44'), ('45', 'TOOTH_45'), ('46', 'TOOTH_46'), ('47', 'TOOTH_47'), ('48', 'TOOTH_48'), ('GUM_UPPER_LEFT_OUTSIDE', 'GUM_UPPER_LEFT_OUTSIDE'), ('GUM_UPPER_FRONT_OUTSIDE', 'GUM_UPPER_FRONT_OUTSIDE'), ('GUM_UPPER_RIGHT_OUTSIDE', 'GUM_UPPER_RIGHT_OUTSIDE'), ('GUM_LOWER_LEFT_OUTSIDE', 'GUM_LOWER_LEFT_OUTSIDE'), ('GUM_LOWER_FRONT_OUTSIDE', 'GUM_LOWER_FRONT_OUTSIDE'), ('GUM_LOWER_RIGHT_OUTSIDE', 'GUM_LOWER_RIGHT_OUTSIDE'), ('ROOF', 'ROOF'), ('TONGUE', 'TONGUE')], default='11', max_length=50),
        ),
    ]
