# Generated by Django 4.2.16 on 2024-11-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_scanresult_tooth_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='questionnaire_answers',
        ),
        migrations.AddField(
            model_name='user',
            name='questionnaire_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
