# Generated by Django 4.2.16 on 2024-11-27 21:18

import api.models.scan_photo
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_scan_questionnaire_answers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanphoto",
            name="file",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[600, 1000],
                upload_to=api.models.scan_photo.file_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="scanphoto",
            name="type",
            field=models.CharField(
                choices=[
                    ("FRONT", "FRONT"),
                    ("RIGHT", "RIGHT"),
                    ("LEFT", "LEFT"),
                    ("LOWER", "LOWER"),
                    ("UPPER", "UPPER"),
                ],
                default="FRONT",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="questionnaire_answers",
            field=models.JSONField(blank=True, max_length=1000, null=True),
        ),
    ]
