# Generated by Django 4.2.16 on 2024-12-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_scanphoto_file_alter_scanphoto_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='risk',
            field=models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
