# Generated by Django 4.2.16 on 2024-12-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_scan_risk_scan_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='error_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('INITIALIZED', 'INITIALIZED'), ('PHOTOS_FINISHED', 'PHOTOS_FINISHED'), ('FINISHED', 'FINISHED'), ('ERROR', 'ERROR')], default='INITIALIZED', max_length=50),
        ),
    ]
