# Generated by Django 4.2.16 on 2024-12-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_scan_error_message_alter_scan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='internal_error_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
