# Generated by Django 4.2.16 on 2024-12-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_validation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
