# Generated by Django 4.2.16 on 2024-12-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_last_validation_email_sent_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_validation_email_sent_at',
            new_name='last_change_password_email_sent_at',
        ),
    ]
