# Generated by Django 4.2.16 on 2024-12-20 22:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_last_validation_email_sent_at_user_last_change_password_email_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model', models.CharField(choices=[('chatgpt-4o', 'CHATGPT_4o'), ('chatgpto4-mini', 'CHATGPT_4o_mini')], default='chatgpt-4o', max_length=70)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_processes', to='api.scan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
