# Generated by Django 4.2.16 on 2024-12-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_scanprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='tokens_used',
        ),
        migrations.AlterField(
            model_name='scanprocess',
            name='model',
            field=models.CharField(choices=[('chatgpt-4o', 'CHATGPT_4o'), ('chatgpt-4o-mini', 'CHATGPT_4o_mini')], default='chatgpt-4o', max_length=70),
        ),
    ]
